version: "3.9"

networks:
  event_network:
    driver: bridge

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - event_network

  rabbit_mq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672



