"""change equipment class field

Revision ID: 0b96c0953795
Revises: 8a1b0fd771ca
Create Date: 2022-08-31 04:42:25.003254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b96c0953795'
down_revision = '8a1b0fd771ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('eq_class', sa.Enum('tent', 'sleeping_bag', 'tourist_foam', name='equipmentclass'), nullable=True))
    op.drop_column('equipment', 'class')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('class', postgresql.ENUM('tent', 'sleeping_bag', 'tourist_foam', name='equipmentclass'), autoincrement=False, nullable=True))
    op.drop_column('equipment', 'eq_class')
    # ### end Alembic commands ###
